# Generated by Django 5.2.7 on 2025-11-05 10:45

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('0', 'سفید'), ('1', 'مشکی'), ('2', 'آبی'), ('3', 'قرمز')], max_length=1, null=True, verbose_name='رنگ'),
        ),
    ]
