# Generated by Django 5.2.7 on 2025-11-09 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_comment_date_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatures',
            name='amount',
            field=models.CharField(max_length=127, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='امتیاز'),
        ),
    ]
